%This function imports isokinetic data for Subjects, Age, Gender, Weight, Day 1,
%Day 2, Day 3


function [SubjectID1, Age1, Gender1, Weight1, Day4, Day5, Day6] = importfile(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  [SUBJECTID1, AGE1, GENDER1, WEIGHT1, DAY4, DAY5, DAY6] =
%  IMPORTFILE1(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as column vectors.
%
%  [SUBJECTID1, AGE1, GENDER1, WEIGHT1, DAY4, DAY5, DAY6] =
%  IMPORTFILE1(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  [SubjectID1, Age1, Gender1, Weight1, Day4, Day5, Day6] = importfile1("/Users/user/Documents/GitHub/MikaylaKINE6203Solutions/isok_data_6803.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Nov-2021 11:12:37

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["SubjectID1", "Age1", "Gender1", "Weight1", "Day4", "Day5", "Day6"];
opts.VariableTypes = ["double", "double", "categorical", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Gender1", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "SubjectID1", "TrimNonNumeric", true);
opts = setvaropts(opts, "SubjectID1", "ThousandsSeparator", ",");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
SubjectID1 = tbl.SubjectID1;
Age1 = tbl.Age1;
Gender1 = tbl.Gender1;
Weight1 = tbl.Weight1;
Day4 = tbl.Day4;
Day5 = tbl.Day5;
Day6 = tbl.Day6;
end